# Generated by Django 6.1 on 2026-08-21 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactInquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Client Name')),
                ('email', models.EmailField(max_length=254, verbose_name='Email Address')),
                ('phone', models.CharField(blank=True, max_length=30, verbose_name='Phone / WhatsApp')),
                ('subject', models.CharField(max_length=200, verbose_name='Project / Subject')),
                ('message', models.TextField(verbose_name='Inquiry Message')),
                ('is_read', models.BooleanField(default=False, verbose_name='Read Status')),
                ('is_replied', models.BooleanField(default=False, verbose_name='Replied')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date Received')),
            ],
            options={
                'verbose_name': 'Client Inquiry',
                'verbose_name_plural': 'Client Inquiries',
                'ordering': ['-created_at'],
            },
        ),
    ]
