# Generated by Django 6.1 on 2026-08-17 10:08

import apps.scheduling.models
import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_reference', models.CharField(db_index=True, default=apps.scheduling.models.generate_booking_reference, max_length=20, unique=True)),
                ('client_name', models.CharField(max_length=120)),
                ('client_email', models.EmailField(max_length=254)),
                ('client_phone', models.CharField(max_length=30)),
                ('company_or_brand', models.CharField(blank=True, max_length=150, verbose_name='Company / Brand Name')),
                ('design_brief', models.TextField(help_text='Describe your project, style, goals, or color preferences', verbose_name='Design Brief / Scope')),
                ('brand_assets_link', models.URLField(blank=True, help_text='Link to Google Drive, Dropbox, Figma, Pinterest board', verbose_name='Brand Assets / Reference Link')),
                ('target_deadline', models.DateField(blank=True, null=True, verbose_name='Target Project Deadline')),
                ('appointment_date', models.DateField(db_index=True)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('meeting_type', models.CharField(choices=[('GOOGLE_MEET', 'Google Meet (Video)'), ('ZOOM', 'Zoom Conference'), ('PHONE', 'Phone / WhatsApp Call'), ('STUDIO', 'In-Person Studio Meeting')], default='GOOGLE_MEET', max_length=30)),
                ('meeting_link', models.CharField(blank=True, default='https://meet.google.com/apx-dsgn-ses', max_length=255)),
                ('status', models.CharField(choices=[('PENDING', 'Pending Confirmation'), ('CONFIRMED', 'Confirmed'), ('IN_PROGRESS', 'In Progress / Designing'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled'), ('RESCHEDULED', 'Rescheduled')], db_index=True, default='CONFIRMED', max_length=20)),
                ('designer_notes', models.TextField(blank=True, help_text='Private internal notes for the designer')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Design Appointment',
                'verbose_name_plural': 'Design Appointments',
                'ordering': ['-appointment_date', '-start_time'],
            },
        ),
        migrations.CreateModel(
            name='BlackoutDate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('reason', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Blackout / Holiday Date',
                'verbose_name_plural': 'Blackout / Holiday Dates',
                'ordering': ['start_date'],
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('category', models.CharField(choices=[('branding', 'Branding & Identity'), ('flyers', 'Flyers & Event Posters'), ('social', 'Social Media & Creatives'), ('infographics', 'Infographics & Corporate Visuals'), ('consultation', 'Design Consultation & Strategy')], default='branding', max_length=40)),
                ('tagline', models.CharField(blank=True, help_text='Short engaging summary', max_length=200)),
                ('description', models.TextField()),
                ('deliverables', models.TextField(help_text='Comma-separated or bullet list of deliverables')),
                ('duration_minutes', models.PositiveIntegerField(default=60, help_text='Duration of initial briefing/consultation in minutes')),
                ('buffer_minutes', models.PositiveIntegerField(default=15, help_text='Buffer time after appointment for notes/setup')),
                ('price', models.DecimalField(decimal_places=2, default=150.0, max_digits=10)),
                ('currency', models.CharField(default='$', max_length=10)),
                ('turnaround_time', models.CharField(default='3-5 Business Days', help_text='Estimated project delivery time', max_length=50)),
                ('badge_text', models.CharField(blank=True, help_text="E.g. 'Most Popular', 'Fast Delivery'", max_length=50)),
                ('icon', models.CharField(default='palette', help_text='Lucide/Feather icon name', max_length=50)),
                ('gradient', models.CharField(default='linear-gradient(135deg, #6366f1 0%, #8b5cf6 100%)', max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Design Service',
                'verbose_name_plural': 'Design Services',
                'ordering': ['order', 'price'],
            },
        ),
        migrations.CreateModel(
            name='WorkingHours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.IntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')], unique=True)),
                ('start_time', models.TimeField(default=datetime.time(9, 0))),
                ('end_time', models.TimeField(default=datetime.time(17, 0))),
                ('break_start', models.TimeField(blank=True, default=datetime.time(13, 0), null=True)),
                ('break_end', models.TimeField(blank=True, default=datetime.time(14, 0), null=True)),
                ('is_off', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Working Hours',
                'verbose_name_plural': 'Working Hours',
                'ordering': ['day_of_week'],
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=100)),
                ('client_role', models.CharField(default='Client & Brand Owner', max_length=100)),
                ('service_name', models.CharField(blank=True, max_length=100)),
                ('rating', models.PositiveIntegerField(default=5)),
                ('comment', models.TextField()),
                ('is_featured', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('appointment', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='review', to='scheduling.appointment')),
            ],
            options={
                'verbose_name': 'Client Review',
                'verbose_name_plural': 'Client Reviews',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PortfolioItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('category', models.CharField(choices=[('branding', 'Branding & Identity'), ('flyers', 'Flyers & Event Posters'), ('social', 'Social Media & Creatives'), ('infographics', 'Infographics & Corporate Visuals'), ('consultation', 'Design Consultation & Strategy')], default='branding', max_length=40)),
                ('client_name', models.CharField(blank=True, max_length=100)),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='portfolio/')),
                ('static_image_path', models.CharField(blank=True, help_text='Static relative image path if image field is not set', max_length=255)),
                ('tools_used', models.CharField(default='Adobe Photoshop, Illustrator, Figma', max_length=200)),
                ('is_featured', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('related_service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='portfolio_items', to='scheduling.service')),
            ],
            options={
                'verbose_name': 'Portfolio Item',
                'verbose_name_plural': 'Portfolio Items',
                'ordering': ['order', '-created_at'],
            },
        ),
        migrations.AddField(
            model_name='appointment',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='appointments', to='scheduling.service'),
        ),
    ]
